name: Using GitHub Actions to run Cycle features!

on:
  push:

jobs:
  Run-Cycle-Feature-POC:
    runs-on: self-hosted
    steps:
      # - name: Use a secret
      #   env:
      #     CI_CYCLE_AUTH: ${{ secrets.CI_CYCLE_AUTH }}
      #     CI_CYCLE_AUTH_SECRET: ${{ secrets.CI_CYCLE_AUTH_SECRET }}
      
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
            
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - run: echo "🖥️ This job is now running on a self-hosted Windows runner named ${{ runner.name	}} !"

      - name: Show Runner OS
        run: echo "The operating system of the runner is ${{ runner.os }}"
        
      - name: Show Runner Workspace
        run: echo "The workspace of the runner is ${{ runner.workspace }}"
        
      - name: List files in the repository
        run: Get-ChildItem -Path ${{ github.workspace }}
      
      - name: Get Cycle-CLI version
        run: cycle-cli.exe -v
      
      - name: Cycle CLI - Run API Test
        run: cycle-cli --clientid ${{ secrets.CI_CYCLE_AUTH }} --client-credential ${{ secrets.CI_CYCLE_AUTH_SECRET }} -p automated-regression-testing.cycproj -u cyclejenkinsuser.cycuser --skip-initial-purge features/api-test-updated.feature
      
      - name: Cycle CLI - Run Browser Test
        run: cycle-cli --clientid ${{ secrets.CI_CYCLE_AUTH }} --client-credential ${{ secrets.CI_CYCLE_AUTH_SECRET }} -p automated-regression-testing.cycproj -u cyclejenkinsuser.cycuser --skip-initial-purge features/grocer.feature
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cycle-reports
          path: C:\actions-runner\_work\cycle-gha-example\cycle-gha-example\featureReports\

        
      - run: echo "🍏 This job's status is ${{ job.status }}."
